name: Sync Fork 

on:
  push: # push 时触发
  schedule:
    - cron: '0 22 * * *' # 每早上6点触发
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: q1lon # 
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch